name: chatr
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.1
  googleapis_auth: ^2.0.0
  http: ^1.5.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon_small.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon_small.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/app_icon_small.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon_small.png"

flutter:
  uses-material-design: true
  assets:
    - assets/service_account.json
    - assets/icons/
